- name: Activate virtual environment on n2
  hosts: n2
  become: true
  tasks: 
    - name: activate virtual environment
      shell: "source /home/ec2-user/venv/bin/activate"

- name: Activate virtual environment on other hosts
  hosts: all:!n2
  become: true
  tasks:
    - name: activate virtual environment on other hosts
      shell: "source /~/flask-app/venv/bin/activate"




   