---
- name: setup flask environment
  hosts: all
  become: true
  remote_user: root

  tasks:
    - name: update apt cache
      apt:
        update_cache: yes
      when: ansible_pkg_mgr == "apt"

    - name: update dnf cache
      dnf:
        update_cache: yes
      when: ansible_pkg_mgr == "dnf"

    - name: update yum cache
      yum:
        update_cache: yes
      when: ansible_pkg_mgr == "yum"

    - name: install necessary packages for apt
      apt:
        name:
          - python3-pip
          - python3-dev
          - build-essential
          - python3-venv
          - git
          - ufw
        state: present
      when: ansible_pkg_mgr == "apt"

    - name: install necessary packages for yum
      yum:
        name:
          - python3-pip
          - python3-devel
          - python3-venv
          - git
        state: present
      when: ansible_pkg_mgr == "yum"

    - name: install necessary packages for dnf
      dnf:
        name:
          - python3-pip
          - python3-devel
          - python3-venv
          - git
        state: present
      when: ansible_pkg_mgr == "dnf"

    - name: Create a directory for CentOS
      file:
        path: flask_dir
        state: directory
        mode: 0777
        owner: centos
        group: centos
      when: ansible_pkg_mgr == "yum"

    - name: Create a directory for Amazon Linux
      file:
        path: flask_dir
        state: directory
        mode: 0777
        owner: ec2-user
        group: ec2-user
      when: ansible_pkg_mgr == "yum"

    - name: Create a directory for Ubuntu
      file:
        path: flask_dir
        state: directory
        mode: 0777
        owner: ubuntu
        group: ubuntu
      when: ansible_pkg_mgr == "apt"

    - name: remove existing flask_dir
      file: 
        path: ~/flask_dir
        state: absent
      ignore errors: yes

    - name: clone git repository
      git: 
        repo:
        dest: ~/flask_dir/
        version: main

    - name: create virtual environment
      command: python3 -m venv flask_dir/.myenv
      args:
        chdir: "~/"
    
    - name: activate virtual environment
      command: /bin/bash -c "source flask_dir/.myenv/bin/activate"
      args:
        chdir: "~/"

    - name: install flask using pip
      pip:
        name: flask
        executable: ~/flask_dir/.myenv/bin/pip
        state: present
    
    - name: activate virtual environment
      command: /bin/bash -c "source ~/flask_dir/.myenv/bin/activate"
    
    - name: start flask app
      command: /bin/bash -c "export FLASK_APP=~/flask_dir/app.py && ~/flask_dir/.myenv/bin/flask run --host=0.0.0.0 --port=5000 &"