- name: setup flask environment
  hosts: all
  become: true

  vars:
    flask_app_dir: /home/centos/flask-app
    git_hub_repo: https://github.com/ctoweh/flask-app.git 

  tasks:
    - name: Install Git on Amazon Linux
      dnf:
        name: git
        state: present
      when: ansible_pkg_mgr == "dnf" and ansible_distribution == "Amazon"

    - name: Debug Ansible facts for Amazon Linux
      debug: 
        var: ansible_pkg_mgr
      when: ansible_distribution == "Amazon"

    - name: Install Git on CentOS
      yum:
        name: git
        state: present
      when: ansible_pkg_mgr == "yum" and ansible_distribution == "CentOS"

    - name: Install Git on Ubuntu
      apt:
        name: git
        state: present
      when: ansible_pkg_mgr == "apt"

    - name: Install dependencies for dnf (Amazon Linux)
      dnf:
        name:
          - python3-pip
          - python3-devel
          - git
        state: present
      when: ansible_pkg_mgr == "yum" and ansible_distribution == "Amazon"

    - name: Install dependencies for yum (CentOS)
      yum:
        name:
          - python3-pip
          - python3-devel
          - git
        state: present
      when: ansible_pkg_mgr == "yum" and ansible_distribution == "CentOS"

    - name: Install dependencies for apt (Ubuntu)
      apt:
        name:
          - python3-pip
          - python3-dev
          - build-essential
          - git
          - ufw
        state: present
      when: ansible_pkg_mgr == "apt"

    - name: Create flask directory for Amazon Linux
      file:
        path: ~/flask-app
        state: directory
        mode: 0777
        owner: ec2-user
        group: ec2-user
      when: ansible_pkg_mgr == "yum" and ansible_distribution == "Amazon"

    - name: Create flask directory for CentOS
      file:
        path: ~/flask-app
        state: directory
        mode: 0777
        owner: centos
        group: centos
      when: ansible_pkg_mgr == "yum" and ansible_distribution == "CentOS"

    - name: Create flask directory for Ubuntu
      file:
        path: ~/flask-app
        state: directory
        mode: 0777
        owner: ubuntu
        group: ubuntu
      when: ansible_pkg_mgr == "apt"

    - name: Remove existing flask-app
      file:
        path: ~/flask-app
        state: absent
      ignore_errors: yes

    - name: clone git repository
      git: 
        repo: https://github.com/ctoweh/flask-app.git
        dest: ~/flask-app/
        version: main

    - name: Debug information
      debug:
        msg: "ansible_pkg_mgr: {{ ansible_pkg_mgr }}, ansible_distribution: {{ ansible_distribution }}"

    - name: Create virtual environment (Amazon Linux)
      command: python3 -m venv /home/ec2-user/flask-app/.myenv
      args:
        chdir: "~/"
      when: ansible_pkg_mgr == "yum" and ansible_distribution == "Amazon"

    - name: Create virtual environment (CentOS)
      command: python3 -m venv /home/centos/flask-app/.myenv
      args:
        chdir: "~/"
      when: ansible_pkg_mgr == "yum" and ansible_distribution == "CentOS"

    - name: Create virtual environment (Ubuntu)
      command: python3 -m venv home/ubuntu/flask-app/.myenv
      args:
        chdir: "~/"
      when: ansible_pkg_mgr == "apt"

    - name: Install Flask using pip (Amazon Linux)
      pip:
        name: flask
        executable: /home/ec2-user/flask-app/venv/bin/pip
        state: present
      when: ansible_pkg_mgr == "yum" and ansible_distribution == "Amazon"

    - name: Install Flask using pip (CentOS)
      pip:
        name: flask
        executable: /home/centos/flask-app/venv/bin/pip
        state: present
      when: ansible_pkg_mgr == "yum" and ansible_distribution == "CentOS"

    - name: Install Flask using pip (Ubuntu)
      pip:
        name: flask
        executable: /home/ubuntu/flask-app/venv/bin/pip
        state: present
      when: ansible_pkg_mgr == "apt"


- name: Activate virtual environment on n2
  hosts: n2
  become: true
  tasks: 
    - name: activate virtual environmnent
      command: source ~/venv/bin/activate
      args:
        chdir: "~/"
  
- name: Activate virtual environment on other hosts
  hosts: all:!n2
  become: true
  tasks:
    - name: activate virtual environment on other hosts
      command: source ~/flask-app/venv/bin/activate
      args:
        chdir: "~/flask-app/"


- name: Start Flask app
  shell: >
     source ~/flask-app/.venv/bin/activate &&
     export FLASK_APP=~/flask-app/app.py &&
     ~/flask-app/.venv/bin/flask run --host=0.0.0.0 --port=5000 
   async: 0
   poll: 0
