---
- name: Configure servers 
  hosts: all
  become: true
  vars:
    app_directory: "/home/{{ ansible_user }}/flask-app"
    git_repo_url: "https://github.com/ctoweh/flask_web_app.git"

  tasks:
    - name: Install git
      package:
        name: git
        state: present

    - name: Create flask-app directory if it doesn't exist
      ansible.builtin.file:
        path: "{{ app_directory }}"
        state: directory
        mode: '0755'

    - name: Clone Github repository
      ansible.builtin.git: 
        repo: "{{ git_repo_url }}"
        dest: "{{ app_directory }}/repository"

    - name: Install Python 3 and pip
      package:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
      when: ansible_distribution == 'CentOS'

    - name: Install Python 3 and pip
      package:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-venv
      when: ansible_distribution == 'Ubuntu'

    - name: Ensure virtualenv is installed
      pip:
        name: virtualenv
        executable: pip3
        state: present

    - name: Create a virtual environment
      command: virtualenv -p python3 venv
      args:
        chdir: "{{ app_directory }}/repository"

    - name: Activate virtual environment
      shell:
        cmd: "source {{ app_directory }}/repository/venv/bin/activate && python --version"
      args:
        executable: /bin/bash

    - name: Install flask within virtual environment
      pip: 
        name: flask
        executable: pip
        state: present

    - name: Run flask app
      command: nohup python3 app.py &
      async: 60
      poll: 0
      args:
        chdir: "{{ app_directory }}/repository"

    - name: Get the PID of the flask app
      shell: "ps aux | grep 'python3 app.py' | grep -v grep | awk '{print $2}'"
      register: flask_pid
      ignore_errors: true

    - name: Stop flask app after 60 seconds
      shell: "sleep 60 && kill -TERM {{ flask_pid.stdout }}"
      ignore_errors: true
