---
- name: Configure servers 
  hosts: all
  become: true
  vars_prompt:
    - name: "os_family"
      prompt: "Enter the OS family of your target hosts (Debian, RedHat)"
      private: no
  vars:
    app_directory: "/home/{{ ansible_user }}/flask-app"
    git_repo_url: "https://github.com/ctoweh/flask_web_app.git"

  tasks:
    - name: Install Git
      package:
        name: git
        state: present
      when: os_family == 'Debian' or os_family == 'RedHat'

    - name: Install necessary system packages
      package:
        name: "{{ item }}"
        state: present
      loop:
        - python3-pip  # Example of a system package needed for Flask app
        # Add any other system packages needed for your Flask app
      when: os_family == 'Debian'

    - name: Install necessary system packages on CentOS
      dnf:
        name: python3-pip
        state: present
      when: os_family == 'RedHat'

    - name: Create flask-app directory if it doesn't exist
      ansible.builtin.file:
        path: "{{ app_directory }}"
        state: directory
        mode: '0755'

    - name: Clone Github repository
      git: 
        repo: "{{ git_repo_url }}"
        dest: "{{ app_directory }}/repository"

    - name: Install Python on CentOS
      yum:
        name: python3
        state: present
      when: ansible_distribution == 'CentOS'

    - name: Install Python on Ubuntu
      apt:
        name: python3
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Install virtualenv package
      pip:
        name: virtualenv
        state: present

    - name: Create a virtual environment
      ansible.builtin.command: virtualenv -p python3 venv
      args:
        chdir: "{{ app_directory }}/repository"

    - name: Activate virtual environment
      ansible.builtin.shell: "{{ app_directory }}/repository/venv/bin/activate"

    - name: Install flask within virtual environment
      pip: 
        name: flask
        state: present

    - name: Run flask app
      ansible.builtin.command: nohup python3 app.py &
      async: 60
      poll: 0
      args:
        chdir: "{{ app_directory }}/repository"

    - name: Get the PID of the flask app
      ansible.builtin.shell: "ps aux | grep 'python3 app.py' | grep -v grep | awk '{print $2}'"
      register: flask_pid
      ignore_errors: yes

    - name: Stop flask app after 60 seconds
      ansible.builtin.shell: "sleep 60 && kill -TERM {{ flask_pid.stdout }}"
      ignore_errors: yes
