---
- name: Activate virtual environment on n1
  hosts: n1
  become: true
  tasks: 
    - name: activate virtual environment
      shell: "source /home/centos/flask-app/venv/bin/activate"

- name: Activate virtual environment on n2
  hosts: n2
  become: true
  tasks: 
    - name: activate virtual environment
      shell: "source /home/ec2-user/venv/bin/activate"

- name: Activate virtual environment on n3
  hosts: n3
  become: true
  tasks:
    - name: activate virtual environment
      command: "source /home/ubuntu/flask-app/venv/bin/activate"




   