---
- name: Configure servers 
  hosts: all
  become: true
  vars:
    app_directory: "/home/{{ ansible_user }}/flask-app"
    git_repo_url: "https://github.com/ctoweh/flask_web_app.git"

  tasks:
    - name: Install git using dnf on CentOS 8
      ansible.builtin.package:
        name: git
        state: present
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '8'

    - name: Install git using yum on CentOS 7
      ansible.builtin.package:
        name: git
        state: present
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

    - name: Install git using apt on Ubuntu
      ansible.builtin.package:
        name: git
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Create flask-app directory if it doesn't exist
      ansible.builtin.file:
        path: "{{ app_directory }}"
        state: directory
        mode: '0755'

    - name: Clone Github repository
      ansible.builtin.git: 
        repo: "{{ git_repo_url }}"
        dest: "{{ app_directory }}/repository"

    - name: Install Python 3 and pip
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip

    - name: Ensure python3-venv is installed
      ansible.builtin.package:
        name: python3-venv
        state: present
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Ubuntu'

    - name: Create a virtual environment
      ansible.builtin.command: python3 -m venv "{{ app_directory }}/venv"

    - name: Activate virtual environment
      ansible.builtin.shell: |
        source "{{ app_directory }}/venv/bin/activate" && python --version
      args:
        executable: /bin/bash

    - name: Install flask within virtual environment
      ansible.builtin.command: pip install flask
      args:
        chdir: "{{ app_directory }}/repository"
