---
- name: Environment setup
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Ensure flask repository directory exists
      file:
        path: "/home/{{ ansible_user }}/flask-app/repository"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0755"

    - name: Ensure virtual environment directory exists
      file:
        path: "/home/{{ ansible_user }}/flask-app/repository/venv"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0755"

    - name: Install Git
      package:
        name: git
        state: present

    - name: Clone GitHub repository
      git:
        repo: "https://github.com/ctoweh/flask-app.git"
        dest: "/home/{{ ansible_user }}/flask-app/repository"
        version: main

    - name: Install virtualenv package
      pip:
        name: virtualenv
        executable: /usr/bin/pip3
        state: present

    - name: Create a virtual environment
      command: virtualenv -p python3 /home/{{ ansible_user }}/flask-app/repository/venv

    - name: Install Flask within the virtual environment
      pip:
        name: flask
        executable: "/home/{{ ansible_user }}/flask-app/repository/venv/bin/pip"
        state: present

    - name: Run Flask app
      command: "/home/{{ ansible_user }}/flask-app/repository/venv/bin/python3 /home/{{ ansible_user }}/flask-app/repository/app.py &"
      async: 60
      poll: 0
      become_user: "{{ ansible_user }}"

    - name: Get the PID of the Flask app
      shell: "ps aux | grep 'python3 /home/{{ ansible_user }}/flask-app/repository/app.py' | grep -v grep | awk '{print $2}'"
      register: flask_pid
      ignore_errors: true

    - name: Stop Flask app after 60 seconds
      shell: "sleep 60 && kill -TERM {{ flask_pid.stdout }}"
      ignore_errors: true
