- name: Activate virtual environment on n2
  hosts: n2
  become: true
  tasks: 
    - name: activate virtual environment
      command: "~/venv/bin/activate"

- name: Activate virtual environment on other hosts
  hosts: all:!n2
  become: true
  tasks:
    - name: activate virtual environment on other hosts
      command: "~/flask-app/venv/bin/activate"



   