---
- name: Activate virtual environment on n1
  hosts: n1
  become: true
  tasks: 
    - name: activate virtual environment
      shell: "source /home/centos/flask-app/venv/bin/activate"

- name: Activate virtual environment on n2
  hosts: n2
  become: true
  tasks: 
    - name: activate virtual environment
      shell: "source /home/ec2-user/flask-app/venv/bin/activate"

- name: Activate virtual environment on n3
  hosts: n3
  become: true
  tasks:
    - name: activate virtual environment
      command: /home/ubuntu/flask-app/venv/bin/activate

- name: Run flask app
  hosts: n1

  vars:
    app_dir: /home/centos/flask-app
    
  tasks:
    - name: run flask app
      command: python {{ app_dir }}/repository/app.py &
      async: 60
      poll: 0
  




   