---
- name: Ubuntu Server Configuration
  hosts: n3
  tasks:
    - name: Install pip
      become: yes
      apt:
        name: python3-pip
        state: present

    - name: Install git
      become: yes
      apt:
        name: git
        state: present

    - name: Create flask-app directory if it doesn't exist
      become: yes
      ansible.builtin.file:
        path: /home/ubuntu/flask-app
        state: directory

    - name: Clone Github repository
      become: yes
      ansible.builtin.git:
        repo: https://github.com/ctoweh/flask_web_app.git
        dest: /home/ubuntu/flask-app
        update: yes

    - name: Generate requirements.txt file
      become: yes
      command: "pip freeze > /home/ubuntu/flask-app/requirements.txt"
      args:
        chdir: "/home/ubuntu/flask-app"
