---
- name: Configure Ubuntu server (n3)
  hosts: n3
  become: true
  vars:
    app_directory: "/home/{{ ansible_user }}/flask-app"
    git_repo_url: "https://github.com/ctoweh/flask_web_app.git"

  tasks:
    - name: Create flask-app directory if it doesn't exist
      ansible.builtin.file:
        path: "{{ app_directory }}"
        state: directory
        mode: '0755'

    - name: Clone Github repository
      ansible.builtin.git: 
        repo: "{{ git_repo_url }}"
        dest: "{{ app_directory }}/repository"

    - name: Install Python 3 and pip
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip

    - name: Ensure python3-venv is installed
      ansible.builtin.package:
        name: python3-venv
        state: present

    - name: Create a virtual environment
      ansible.builtin.command: 
        cmd: python3 -m venv "{{ app_directory }}/venv"

    - name: Activate virtual environment
      ansible.builtin.shell: 
        cmd: source "{{ app_directory }}/venv/bin/activate" && python --version
      args:
        executable: /bin/bash

    - name: Install Flask within virtual environment
      ansible.builtin.command: 
        cmd: pip install flask
      args:
        chdir: "{{ app_directory }}/repository"
