---
- name: Update package cache
  package_facts:
    manager: auto

- name: Upgrade all packages
  package:
    name: "*"
    state: latest
  become: yes

- name: Install Python virtualenv
  package:
    name: python3-virtualenv
    state: present
  become: yes
